/* Copyright 2023-2024 Bryan Wong */

#pragma once

#define UTL_SUPPORTS_TRAIT(TRAIT) UTL_TRAIT_SUPPORTED_##TRAIT
#define UTL_DEFINES_TRAIT(TRAIT) (UTL_SUPPORTS_TRAIT(TRAIT) || UTL_TRAIT_DEFINED_##TRAIT)
